CREATE OR REPLACE FUNCTION EXEMPLO_SIMPLES
RETURN VARCHAR2 IS
BEGIN
   RETURN 'OLÁ, MUNDO!';
END;


CREATE OR REPLACE FUNCTION SAUDACAO_PESSOA (
	NOME IN VARCHAR2, 
	IDADE IN NUMBER
) 
RETURN VARCHAR2 IS
BEGIN
	RETURN 'OLÁ ' || NOME || ', SUA IDADE É ' || IDADE || ' ANOS.';
END;



SELECT SAUDACAO_PESSOA('ODAIR', 34) FROM DUAL

SELECT EXEMPLO_SIMPLES FROM DUAL 