CREATE OR REPLACE FUNCTION HELLO_WORLD
RETURN VARCHAR2 IS
BEGIN
   RETURN 'HELLO WORLD!';
END;

SELECT HELLO_WORLD FROM DUAL 



CREATE OR REPLACE FUNCTION SAUDACAO_PESSOA (
	NOME IN VARCHAR2, 
	IDADE IN NUMBER
) 
RETURN VARCHAR2 IS
BEGIN
	RETURN 'OLÁ ' || NOME || ', SUA IDADE É ' || IDADE || ' ANOS.';
END;



SELECT SAUDACAO_PESSOA('ODAIR', 34) FROM DUAL

